---
- name: Create destination directory
  file:
      path: "{{ path }}"
      state: directory
  tags:
      - nginx-load-balancer

- name: Configure load-balancer
  template:
      src: nginx_lb.conf.j2
      dest: "{{ path }}/nginx_lb.conf"
  tags:
      - nginx-load-balancer
  notify:
      - restart nginx load-balancer container.

- name: Configure Docker Compose
  template:
      src: docker-compose.yml.j2
      dest: "{{ path }}/docker-compose.yml"
  tags:
      - nginx-load-balancer
  notify:
      - restart nginx load-balancer container
