---
- name: Configure
  template:
      src: nginx_lb.conf.j2
      dest: "{{ path }}/config/nginx_lb.conf"
  tags:
      - nginx-load-balancer
  notify:
      - restart nginx load-balancer container
# - name: Loadbalancer - Get setups
#   git:
#     repo: "{{ repo }}"
#     dest: "{{ path }}"
#     accept_hostkey: yes
#   tags:
#     - nginx-load-balancer
# - name: Loadbalancer - Ignore permission changes
#   shell: git config core.fileMode false
#   args:
#     chdir: "{{ path }}"
#   tags:
#     - nginx-load-balancer
#
# - name: Loadbalancer - Run
#   shell: docker-compose up -d
#   args:
#     chdir: "{{ path }}"
#   tags:
#     - nginx-load-balancer
